apiVersion: cninf.aviad.okro.com/v1alpha1
kind: ObjStore
metadata:
  name: aviad-objstore-01
spec:
  name: aviad-objstore-live-01 #will be bucket name, as such must be globally unique
  locked: false
